---
title: Playbook
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  buckets:
    title: Buckets
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/post/:title/"
- scope:
    path: ''
    type: buckets
  values:
    layout: post
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
sass:
  style: compressed
