---
title: Playbook
timezone: America/Chicago
collections:
  buckets:
    title: Buckets
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: general
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: buckets
  values:
    layout: general
    permalink: "/:title/"
    Schedule:
    - Parent: 
      Children:
      - 
    General:
      Column 1:
        Heading: 
        List:
        - 
      Column 2:
        Heading: 
        List:
        - 
permalink: pretty
sass:
  style: compressed
